---

- name: Disable UFW firewall
  ansible.builtin.systemd:
    name: ufw
    state: stopped
    enabled: false
  when:
    - "'ufw.service' in services"
    - services['ufw.service']['status'] != 'not-found'

- name: Disable Netfilter firewall
  ansible.builtin.systemd:
    name: nftables
    state: stopped
    enabled: false
  when:
    - "'nftables.service' in services"
    - services['nftables.service']['status'] != 'not-found'
