---

- name: Install required core packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 604800
  with_items:
  - iptables
  - iptables-persistent
