---

- name: Install required firewall packages for Debian
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
    install_recommends: false
    cache_valid_time: 86400
  vars:
    packages:
      - iptables
      - iptables-persistent
      - ipset
  when: ansible_os_family == 'Debian'

- name: Install required firewall packages for CentOS
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - iptables
      - ipset
  when: ansible_os_family == 'RedHat'
