---

- name: Install required firewall packages for Debian
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 86400
  vars:
    packages:
      - iptables
      - iptables-persistent
  when: ansible_os_family == 'Debian'

- name: Install required firewall packages for CentOS
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - iptables
  when: ansible_os_family == 'RedHat'
