---

- name: Install required firewall packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 604800
  vars:
    packages:
    - iptables
    - iptables-persistent
