---

# Rsyslog configuration

- name: Copy Rsyslog Configurations
  ansible.builtin.copy:
    src: config/rsyslog/
    dest: /etc/rsyslog.d/
    owner: root
    group: root
    mode: 0440
  notify: Restart rsyslog

# Logrotate configuration

- name: Copy logrotate configuration
  ansible.builtin.copy:
    src: config/logrotate/
    dest: /etc/logrotate.d/
