---

# Copyright (c) 2017 Hexanode
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# OS support verification
- name: Check OS support
  fail:
    msg: "Unsupported OS for core users. Currently supported : Debian 8, 9 and Debian 10 and CentOS 8"
  when: >
    (ansible_os_family != 'Debian' and ansible_os_family != 'RedHat')
    or
    (ansible_os_family == 'Debian' and ansible_distribution_major_version is version('8', '<') and ansible_distribution_major_version is version('10', '>'))
    or
    (ansible_os_family == 'RedHat' and ansible_distribution_major_version is version('8', '!='))
  tags: always

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

# Disable other firewall
- name: Dynamic include of disable_others
  include_tasks: disable_others.yml
  when: firewall_disable_others|bool

# Install
- name: Static import of install
  import_tasks: install.yml
  tags: firewall_install

# System
- name: Static import of system configuration
  import_tasks: system.yml
  tags: firewall_system

# Logs
- name: Dynamic include of logs
  include_tasks: logs.yml
  tags: firewall_logs
  when: firewall_log_dropped_packets|bool

# Rules
- name: Static import of rules
  import_tasks: rules.yml
  tags: firewall_rules
