---

# Copyright (c) 2017 Hexanode
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# OS support verification
- name: Check OS support
  fail:
    msg: "Unsupported OS for docker role. Currently supported : Debian 8 & Debian 9"
  when: ansible_os_family != "Debian" and ( ansible_distribution_major_version == "9" or ansible_distribution_major_version == "8" )
  tags: always

# Disable other firewall
- name: Dynamic include of disable_others
  include_tasks: disable_others.yml
  when: firewall_disable_others

# Install
- name: Static import of install
  import_tasks: install.yml
  tags: firewall_install

# System
- name: Static import of system configuration
  import_tasks: system.yml
  tags: firewall_system

# Logs
- name: Dynamic include of logs
  include_tasks: logs.yml
  tags: firewall_logs
  when: firewall_log_dropped_packets

# Rules
- name: Static import of rules
  import_tasks: rules.yml
  tags: firewall_rules
