---

- name: Configure IPv4 Forward
  lineinfile:
    dest: /etc/sysctl.conf
    line: "net.ipv4.ip_forward={{ firewall_allow_ip_forward }}"
    regexp: '^#?net.ipv4.ip_forward=.*$'
    state: present
  when: firewall_allow_ip_forward == '0' or firewall_allow_ip_forward == '1'

- name: Configure IPv6 Forward
  lineinfile:
    dest: /etc/sysctl.conf
    line: "net.ipv6.conf.all.forwarding={{ firewall_allow_ip_forward }}"
    regexp: '^#?net.ipv6.conf.all.forwarding=.*$'
    state: present
  when: firewall_allow_ip_forward == '0' or firewall_allow_ip_forward == '1'
