---

- name: Configure IPv4 Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "{{ '1' if firewall_allow_ip_forwarding|bool else '0' }}"
    state: present
    sysctl_set: yes
    reload: yes

- name: Configure IPv6 Forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "{{ '1' if firewall_allow_ip_forwarding|bool else '0' }}"
    state: present
    sysctl_set: yes
    reload: yes
