---

# Restart Rsyslog handler
- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

# Test IPv4 ruleset
- name: Test IPv4 iptables ruleset
  shell: "iptables-restore -t {{ firewall_dest_ipv4_rules }}"
  listen: Test and Restore IPv4 ruleset
  changed_when: False

# Restore IPv4 Ruleset
- name: Restore IPv4 iptables ruleset
  shell: "iptables-restore < {{ firewall_dest_ipv4_rules }}"
  listen: Test and Restore IPv4 ruleset
  when: firewall_restore_rules|bool

# Test IPv6 ruleset
- name: Test IPv6 iptables ruleset
  shell: "ip6tables-restore -t {{ firewall_dest_ipv6_rules }}"
  listen: Test and Restore IPv6 ruleset
  changed_when: False

# Restore IPv6 Ruleset
- name: Restore IPv6 iptables ruleset
  shell: "ip6tables-restore < {{ firewall_dest_ipv6_rules }}"
  listen: Test and Restore IPv6 ruleset
  when: firewall_restore_rules|bool
